format_version: v1.0
type: UniqueComponent
attributes: {id: pdsSystem}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: BLESTACK_LOADED}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: pdsSystem, value: 'true'}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: NVM_Dependency}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: nvm}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: NVM_MEMORY}
- type: ElementPosition
  attributes: {x: '414', y: '423', id: pdsSystem}
