format_version: v1.0
type: UniqueComponent
attributes: {id: profileBLE_TRP}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: TRP_BOOL_CLIENT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: TRP_BOOL_SERVER}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
- type: ElementPosition
  attributes: {x: '204', y: '306', id: profileBLE_TRP}
