format_version: v1.0
type: UniqueComponent
attributes: {id: svcBLE_DIS}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: DIS_FW_REV_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: String
    attributes: {id: DIS_FW_REV_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 0.7.3.2}
  - type: Boolean
    attributes: {id: DIS_HW_REV_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: String
    attributes: {id: DIS_MANU_NAME_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: MCHP}
  - type: String
    attributes: {id: DIS_MODEL_NUM_STRING}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: Coming Soon}
  - type: Boolean
    attributes: {id: DIS_SERIAL_NUM_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DIS_SW_REV_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Boolean
    attributes: {id: DIS_SYSTEM_ID_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
- type: ElementPosition
  attributes: {x: '652', y: '252', id: svcBLE_DIS}
