format_version: v1.0
configName: wbz451_curiosity_board
folderName: zigbee_ExtendedLight
frameworkPath: C:\mchp
processor: WBZ451
projectName: zigbee_ExtendedLight
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32CX-BZ_DFP\1.0.80\WBZ451\atdf\WBZ451.atdf
